// Country metadata: ISO2 -> { iso2, iso3, name, continent, flagCode }
// flagCode is the 2-letter code used by flagcdn.com (lowercase ISO2)
// Continent groupings follow common conventions; XM = Eurozone aggregate.

export const COUNTRIES = {
  // Eurozone aggregate (used by BIS as "XM")
  XM: { iso2: "XM", iso3: "EMU", name: "Eurozone", continent: "Europe", flagCode: "eu" },

  // Africa
  DZ: { iso2: "DZ", iso3: "DZA", name: "Algeria", continent: "Africa", flagCode: "dz" },
  AO: { iso2: "AO", iso3: "AGO", name: "Angola", continent: "Africa", flagCode: "ao" },
  BW: { iso2: "BW", iso3: "BWA", name: "Botswana", continent: "Africa", flagCode: "bw" },
  CV: { iso2: "CV", iso3: "CPV", name: "Cape Verde", continent: "Africa", flagCode: "cv" },
  CF: { iso2: "CF", iso3: "CAF", name: "Central African States", continent: "Africa", flagCode: "cf" },
  CD: { iso2: "CD", iso3: "COD", name: "DR Congo", continent: "Africa", flagCode: "cd" },
  EG: { iso2: "EG", iso3: "EGY", name: "Egypt", continent: "Africa", flagCode: "eg" },
  SZ: { iso2: "SZ", iso3: "SWZ", name: "Eswatini", continent: "Africa", flagCode: "sz" },
  GM: { iso2: "GM", iso3: "GMB", name: "Gambia", continent: "Africa", flagCode: "gm" },
  GH: { iso2: "GH", iso3: "GHA", name: "Ghana", continent: "Africa", flagCode: "gh" },
  KE: { iso2: "KE", iso3: "KEN", name: "Kenya", continent: "Africa", flagCode: "ke" },
  LS: { iso2: "LS", iso3: "LSO", name: "Lesotho", continent: "Africa", flagCode: "ls" },
  MW: { iso2: "MW", iso3: "MWI", name: "Malawi", continent: "Africa", flagCode: "mw" },
  MU: { iso2: "MU", iso3: "MUS", name: "Mauritius", continent: "Africa", flagCode: "mu" },
  MA: { iso2: "MA", iso3: "MAR", name: "Morocco", continent: "Africa", flagCode: "ma" },
  MZ: { iso2: "MZ", iso3: "MOZ", name: "Mozambique", continent: "Africa", flagCode: "mz" },
  NA: { iso2: "NA", iso3: "NAM", name: "Namibia", continent: "Africa", flagCode: "na" },
  NG: { iso2: "NG", iso3: "NGA", name: "Nigeria", continent: "Africa", flagCode: "ng" },
  RW: { iso2: "RW", iso3: "RWA", name: "Rwanda", continent: "Africa", flagCode: "rw" },
  SC: { iso2: "SC", iso3: "SYC", name: "Seychelles", continent: "Africa", flagCode: "sc" },
  SL: { iso2: "SL", iso3: "SLE", name: "Sierra Leone", continent: "Africa", flagCode: "sl" },
  ZA: { iso2: "ZA", iso3: "ZAF", name: "South Africa", continent: "Africa", flagCode: "za" },
  SS: { iso2: "SS", iso3: "SSD", name: "South Sudan", continent: "Africa", flagCode: "ss" },
  TZ: { iso2: "TZ", iso3: "TZA", name: "Tanzania", continent: "Africa", flagCode: "tz" },
  TN: { iso2: "TN", iso3: "TUN", name: "Tunisia", continent: "Africa", flagCode: "tn" },
  UG: { iso2: "UG", iso3: "UGA", name: "Uganda", continent: "Africa", flagCode: "ug" },
  XA: { iso2: "XA", iso3: "XAF", name: "West African States", continent: "Africa", flagCode: "sn" },
  ZM: { iso2: "ZM", iso3: "ZMB", name: "Zambia", continent: "Africa", flagCode: "zm" },
  ZW: { iso2: "ZW", iso3: "ZWE", name: "Zimbabwe", continent: "Africa", flagCode: "zw" },

  // Americas
  AR: { iso2: "AR", iso3: "ARG", name: "Argentina", continent: "Americas", flagCode: "ar" },
  BS: { iso2: "BS", iso3: "BHS", name: "Bahamas", continent: "Americas", flagCode: "bs" },
  BB: { iso2: "BB", iso3: "BRB", name: "Barbados", continent: "Americas", flagCode: "bb" },
  BO: { iso2: "BO", iso3: "BOL", name: "Bolivia", continent: "Americas", flagCode: "bo" },
  BR: { iso2: "BR", iso3: "BRA", name: "Brazil", continent: "Americas", flagCode: "br" },
  CA: { iso2: "CA", iso3: "CAN", name: "Canada", continent: "Americas", flagCode: "ca" },
  CL: { iso2: "CL", iso3: "CHL", name: "Chile", continent: "Americas", flagCode: "cl" },
  CO: { iso2: "CO", iso3: "COL", name: "Colombia", continent: "Americas", flagCode: "co" },
  CR: { iso2: "CR", iso3: "CRI", name: "Costa Rica", continent: "Americas", flagCode: "cr" },
  CW: { iso2: "CW", iso3: "CUW", name: "Curacao", continent: "Americas", flagCode: "cw" },
  DO: { iso2: "DO", iso3: "DOM", name: "Dominican Republic", continent: "Americas", flagCode: "do" },
  XC: { iso2: "XC", iso3: "XCD", name: "Eastern Caribbean", continent: "Americas", flagCode: "ag" },
  GT: { iso2: "GT", iso3: "GTM", name: "Guatemala", continent: "Americas", flagCode: "gt" },
  HN: { iso2: "HN", iso3: "HND", name: "Honduras", continent: "Americas", flagCode: "hn" },
  JM: { iso2: "JM", iso3: "JAM", name: "Jamaica", continent: "Americas", flagCode: "jm" },
  MX: { iso2: "MX", iso3: "MEX", name: "Mexico", continent: "Americas", flagCode: "mx" },
  NI: { iso2: "NI", iso3: "NIC", name: "Nicaragua", continent: "Americas", flagCode: "ni" },
  PY: { iso2: "PY", iso3: "PRY", name: "Paraguay", continent: "Americas", flagCode: "py" },
  PE: { iso2: "PE", iso3: "PER", name: "Peru", continent: "Americas", flagCode: "pe" },
  SX: { iso2: "SX", iso3: "SXM", name: "Sint Maarten", continent: "Americas", flagCode: "sx" },
  SR: { iso2: "SR", iso3: "SUR", name: "Suriname", continent: "Americas", flagCode: "sr" },
  TT: { iso2: "TT", iso3: "TTO", name: "Trinidad and Tobago", continent: "Americas", flagCode: "tt" },
  US: { iso2: "US", iso3: "USA", name: "United States", continent: "Americas", flagCode: "us" },
  UY: { iso2: "UY", iso3: "URY", name: "Uruguay", continent: "Americas", flagCode: "uy" },
  VE: { iso2: "VE", iso3: "VEN", name: "Venezuela", continent: "Americas", flagCode: "ve" },

  // Asia
  AF: { iso2: "AF", iso3: "AFG", name: "Afghanistan", continent: "Asia", flagCode: "af" },
  AM: { iso2: "AM", iso3: "ARM", name: "Armenia", continent: "Asia", flagCode: "am" },
  AZ: { iso2: "AZ", iso3: "AZE", name: "Azerbaijan", continent: "Asia", flagCode: "az" },
  BH: { iso2: "BH", iso3: "BHR", name: "Bahrain", continent: "Asia", flagCode: "bh" },
  BD: { iso2: "BD", iso3: "BGD", name: "Bangladesh", continent: "Asia", flagCode: "bd" },
  CN: { iso2: "CN", iso3: "CHN", name: "China", continent: "Asia", flagCode: "cn" },
  GE: { iso2: "GE", iso3: "GEO", name: "Georgia", continent: "Asia", flagCode: "ge" },
  HK: { iso2: "HK", iso3: "HKG", name: "Hong Kong", continent: "Asia", flagCode: "hk" },
  IN: { iso2: "IN", iso3: "IND", name: "India", continent: "Asia", flagCode: "in" },
  ID: { iso2: "ID", iso3: "IDN", name: "Indonesia", continent: "Asia", flagCode: "id" },
  IR: { iso2: "IR", iso3: "IRN", name: "Iran", continent: "Asia", flagCode: "ir" },
  IL: { iso2: "IL", iso3: "ISR", name: "Israel", continent: "Asia", flagCode: "il" },
  JP: { iso2: "JP", iso3: "JPN", name: "Japan", continent: "Asia", flagCode: "jp" },
  JO: { iso2: "JO", iso3: "JOR", name: "Jordan", continent: "Asia", flagCode: "jo" },
  KZ: { iso2: "KZ", iso3: "KAZ", name: "Kazakhstan", continent: "Asia", flagCode: "kz" },
  KW: { iso2: "KW", iso3: "KWT", name: "Kuwait", continent: "Asia", flagCode: "kw" },
  KG: { iso2: "KG", iso3: "KGZ", name: "Kyrgyzstan", continent: "Asia", flagCode: "kg" },
  LB: { iso2: "LB", iso3: "LBN", name: "Lebanon", continent: "Asia", flagCode: "lb" },
  MO: { iso2: "MO", iso3: "MAC", name: "Macau", continent: "Asia", flagCode: "mo" },
  MY: { iso2: "MY", iso3: "MYS", name: "Malaysia", continent: "Asia", flagCode: "my" },
  MN: { iso2: "MN", iso3: "MNG", name: "Mongolia", continent: "Asia", flagCode: "mn" },
  OM: { iso2: "OM", iso3: "OMN", name: "Oman", continent: "Asia", flagCode: "om" },
  PK: { iso2: "PK", iso3: "PAK", name: "Pakistan", continent: "Asia", flagCode: "pk" },
  PH: { iso2: "PH", iso3: "PHL", name: "Philippines", continent: "Asia", flagCode: "ph" },
  QA: { iso2: "QA", iso3: "QAT", name: "Qatar", continent: "Asia", flagCode: "qa" },
  SA: { iso2: "SA", iso3: "SAU", name: "Saudi Arabia", continent: "Asia", flagCode: "sa" },
  KR: { iso2: "KR", iso3: "KOR", name: "South Korea", continent: "Asia", flagCode: "kr" },
  LK: { iso2: "LK", iso3: "LKA", name: "Sri Lanka", continent: "Asia", flagCode: "lk" },
  TW: { iso2: "TW", iso3: "TWN", name: "Taiwan", continent: "Asia", flagCode: "tw" },
  TJ: { iso2: "TJ", iso3: "TJK", name: "Tajikistan", continent: "Asia", flagCode: "tj" },
  TH: { iso2: "TH", iso3: "THA", name: "Thailand", continent: "Asia", flagCode: "th" },
  TR: { iso2: "TR", iso3: "TUR", name: "Turkey", continent: "Asia", flagCode: "tr" },
  AE: { iso2: "AE", iso3: "ARE", name: "United Arab Emirates", continent: "Asia", flagCode: "ae" },
  UZ: { iso2: "UZ", iso3: "UZB", name: "Uzbekistan", continent: "Asia", flagCode: "uz" },
  VN: { iso2: "VN", iso3: "VNM", name: "Vietnam", continent: "Asia", flagCode: "vn" },

  // Europe
  AL: { iso2: "AL", iso3: "ALB", name: "Albania", continent: "Europe", flagCode: "al" },
  BY: { iso2: "BY", iso3: "BLR", name: "Belarus", continent: "Europe", flagCode: "by" },
  BG: { iso2: "BG", iso3: "BGR", name: "Bulgaria", continent: "Europe", flagCode: "bg" },
  CZ: { iso2: "CZ", iso3: "CZE", name: "Czech Republic", continent: "Europe", flagCode: "cz" },
  DK: { iso2: "DK", iso3: "DNK", name: "Denmark", continent: "Europe", flagCode: "dk" },
  HU: { iso2: "HU", iso3: "HUN", name: "Hungary", continent: "Europe", flagCode: "hu" },
  IS: { iso2: "IS", iso3: "ISL", name: "Iceland", continent: "Europe", flagCode: "is" },
  MD: { iso2: "MD", iso3: "MDA", name: "Moldova", continent: "Europe", flagCode: "md" },
  MK: { iso2: "MK", iso3: "MKD", name: "North Macedonia", continent: "Europe", flagCode: "mk" },
  NO: { iso2: "NO", iso3: "NOR", name: "Norway", continent: "Europe", flagCode: "no" },
  PL: { iso2: "PL", iso3: "POL", name: "Poland", continent: "Europe", flagCode: "pl" },
  RO: { iso2: "RO", iso3: "ROU", name: "Romania", continent: "Europe", flagCode: "ro" },
  RU: { iso2: "RU", iso3: "RUS", name: "Russia", continent: "Europe", flagCode: "ru" },
  RS: { iso2: "RS", iso3: "SRB", name: "Serbia", continent: "Europe", flagCode: "rs" },
  SE: { iso2: "SE", iso3: "SWE", name: "Sweden", continent: "Europe", flagCode: "se" },
  CH: { iso2: "CH", iso3: "CHE", name: "Switzerland", continent: "Europe", flagCode: "ch" },
  UA: { iso2: "UA", iso3: "UKR", name: "Ukraine", continent: "Europe", flagCode: "ua" },
  GB: { iso2: "GB", iso3: "GBR", name: "United Kingdom", continent: "Europe", flagCode: "gb" },

  // Eurozone-discontinued legacy series in BIS (Germany, France, Italy, etc.) — keep for history
  DE: { iso2: "DE", iso3: "DEU", name: "Germany (legacy)", continent: "Europe", flagCode: "de" },
  FR: { iso2: "FR", iso3: "FRA", name: "France (legacy)", continent: "Europe", flagCode: "fr" },
  IT: { iso2: "IT", iso3: "ITA", name: "Italy (legacy)", continent: "Europe", flagCode: "it" },
  ES: { iso2: "ES", iso3: "ESP", name: "Spain (legacy)", continent: "Europe", flagCode: "es" },
  NL: { iso2: "NL", iso3: "NLD", name: "Netherlands (legacy)", continent: "Europe", flagCode: "nl" },
  BE: { iso2: "BE", iso3: "BEL", name: "Belgium (legacy)", continent: "Europe", flagCode: "be" },
  AT: { iso2: "AT", iso3: "AUT", name: "Austria (legacy)", continent: "Europe", flagCode: "at" },
  IE: { iso2: "IE", iso3: "IRL", name: "Ireland (legacy)", continent: "Europe", flagCode: "ie" },
  PT: { iso2: "PT", iso3: "PRT", name: "Portugal (legacy)", continent: "Europe", flagCode: "pt" },
  GR: { iso2: "GR", iso3: "GRC", name: "Greece (legacy)", continent: "Europe", flagCode: "gr" },
  FI: { iso2: "FI", iso3: "FIN", name: "Finland (legacy)", continent: "Europe", flagCode: "fi" },
  LU: { iso2: "LU", iso3: "LUX", name: "Luxembourg (legacy)", continent: "Europe", flagCode: "lu" },
  HR: { iso2: "HR", iso3: "HRV", name: "Croatia", continent: "Europe", flagCode: "hr" },
  SK: { iso2: "SK", iso3: "SVK", name: "Slovakia", continent: "Europe", flagCode: "sk" },
  SI: { iso2: "SI", iso3: "SVN", name: "Slovenia", continent: "Europe", flagCode: "si" },
  EE: { iso2: "EE", iso3: "EST", name: "Estonia", continent: "Europe", flagCode: "ee" },
  LV: { iso2: "LV", iso3: "LVA", name: "Latvia", continent: "Europe", flagCode: "lv" },
  LT: { iso2: "LT", iso3: "LTU", name: "Lithuania", continent: "Europe", flagCode: "lt" },
  CY: { iso2: "CY", iso3: "CYP", name: "Cyprus", continent: "Europe", flagCode: "cy" },
  MT: { iso2: "MT", iso3: "MLT", name: "Malta", continent: "Europe", flagCode: "mt" },

  // Oceania
  AU: { iso2: "AU", iso3: "AUS", name: "Australia", continent: "Oceania", flagCode: "au" },
  NZ: { iso2: "NZ", iso3: "NZL", name: "New Zealand", continent: "Oceania", flagCode: "nz" },
  FJ: { iso2: "FJ", iso3: "FJI", name: "Fiji", continent: "Oceania", flagCode: "fj" },
  PG: { iso2: "PG", iso3: "PNG", name: "Papua New Guinea", continent: "Oceania", flagCode: "pg" },
  WS: { iso2: "WS", iso3: "WSM", name: "Samoa", continent: "Oceania", flagCode: "ws" },
};

// Name -> ISO2 map for Wikipedia normalization
export const NAME_TO_ISO2 = {
  "Afghanistan": "AF",
  "Albania": "AL",
  "Algeria": "DZ",
  "Angola": "AO",
  "Argentina": "AR",
  "Armenia": "AM",
  "Australia": "AU",
  "Azerbaijan": "AZ",
  "Bahamas": "BS",
  "Bahrain": "BH",
  "Bangladesh": "BD",
  "Barbados": "BB",
  "Belarus": "BY",
  "Bolivia": "BO",
  "Botswana": "BW",
  "Brazil": "BR",
  "Bulgaria": "BG",
  "Canada": "CA",
  "Cape Verde": "CV",
  "Central African States": "CF",
  "Chile": "CL",
  "China": "CN",
  "Colombia": "CO",
  "Costa Rica": "CR",
  "DR Congo": "CD",
  "Curacao": "CW",
  "Czech Republic": "CZ",
  "Denmark": "DK",
  "Dominican Republic": "DO",
  "Eastern Caribbean": "XC",
  "Egypt": "EG",
  "Eswatini": "SZ",
  "Eurozone": "XM",
  "Fiji": "FJ",
  "Gambia": "GM",
  "Georgia": "GE",
  "Ghana": "GH",
  "Guatemala": "GT",
  "Honduras": "HN",
  "Hong Kong": "HK",
  "Hungary": "HU",
  "Iceland": "IS",
  "India": "IN",
  "Indonesia": "ID",
  "Iran": "IR",
  "Israel": "IL",
  "Jamaica": "JM",
  "Japan": "JP",
  "Jordan": "JO",
  "Kazakhstan": "KZ",
  "Kenya": "KE",
  "Kuwait": "KW",
  "Kyrgyzstan": "KG",
  "Lebanon": "LB",
  "Lesotho": "LS",
  "Macau": "MO",
  "Malawi": "MW",
  "Malaysia": "MY",
  "Mauritius": "MU",
  "Mexico": "MX",
  "Moldova": "MD",
  "Mongolia": "MN",
  "Morocco": "MA",
  "Mozambique": "MZ",
  "Namibia": "NA",
  "New Zealand": "NZ",
  "Nicaragua": "NI",
  "Nigeria": "NG",
  "North Macedonia": "MK",
  "Norway": "NO",
  "Oman": "OM",
  "Pakistan": "PK",
  "Papua New Guinea": "PG",
  "Paraguay": "PY",
  "Peru": "PE",
  "Philippines": "PH",
  "Poland": "PL",
  "Qatar": "QA",
  "Romania": "RO",
  "Russia": "RU",
  "Rwanda": "RW",
  "Samoa": "WS",
  "Saudi Arabia": "SA",
  "Serbia": "RS",
  "Seychelles": "SC",
  "Sierra Leone": "SL",
  "Sint Maarten": "SX",
  "South Africa": "ZA",
  "South Korea": "KR",
  "South Sudan": "SS",
  "Sri Lanka": "LK",
  "Suriname": "SR",
  "Sweden": "SE",
  "Switzerland": "CH",
  "Taiwan": "TW",
  "Tajikistan": "TJ",
  "Tanzania": "TZ",
  "Thailand": "TH",
  "Trinidad and Tobago": "TT",
  "Tunisia": "TN",
  "Turkey": "TR",
  "Uganda": "UG",
  "Ukraine": "UA",
  "UAE": "AE",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States": "US",
  "Uruguay": "UY",
  "Uzbekistan": "UZ",
  "Venezuela": "VE",
  "Vietnam": "VN",
  "West African States": "XA",
  "Zambia": "ZM",
  "Zimbabwe": "ZW",
};
